FROM quay.io/podman/stable:latest

LABEL org.opencontainers.image.source https://github.com/ivanfed0t0v/images

LABEL devcontainer.metadata='[{ \
  "overrideCommand": false, \
  "privileged": false, \
  "remoteUser": "podman", \
  "runArgs": [ \
    "--cap-drop", "ALL", \
    "--device", "/dev/fuse", \
    "--image-volume", "ignore", \
    "--ipc", "none", \
    "--no-hosts", \
    "--pull", "newer" \
  ], \
  "securityOpt": [ "label=disable" ], \
  "updateRemoteUserUID": false \
}]'

RUN dnf -y update && \
    dnf -y install git fish && \
    dnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.* && \
    export DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') && \
    curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.rpm && \
    rpm -i dive_${DIVE_VERSION}_linux_amd64.rpm

ENV HOME=/home/podman
USER podman
CMD ["sleep", "infinity"]
