FROM quay.io/curl/curl-base:latest as dl

WORKDIR /dl
RUN curl -Lo chezmoi.tar.gz https://github.com/twpayne/chezmoi/releases/download/v2.36.0/chezmoi_2.36.0_linux-glibc_amd64.tar.gz && \
    tar xf chezmoi.tar.gz


FROM gcr.io/distroless/base:latest

LABEL org.opencontainers.image.source https://github.com/ivanfed0t0v/images

COPY --from=dl --chmod=755 /dl/chezmoi /bin/chezmoi

ENTRYPOINT ["/bin/chezmoi"]
